app:
    resource: '@AppBundle/Controller/'
    type: annotation

home:
    path:     /index
    defaults: { _controller: AppBundle:University:home }

teacherdetails:
    path:     api/getteacherdetails/{tid}
    defaults: { _controller: AppBundle:University:teacherProfile }
    methods:  [GET]

teachersignup:
    path:     /api/teacher/signup
    defaults: { _controller: AppBundle:University:signupTeacher }
    methods:  [POST]
teachersignupverify:
    path:     api/teacher/verify/{verifyLink}
    defaults: { _controller: AppBundle:University:verifySignupteacher}
    methods:  [GET]
studentsignupverify:
    path:     api/student/verify/{verifyLink}
    defaults: { _controller: AppBundle:University:verifySignupStudent}
    methods:  [GET]

teacherstatus:
    path:     /api/teacher/status
    defaults: { _controller: AppBundle:University:teacherStatus }
    methods:  [POST]

saveteacher:
    path:     /api/saveteacher
    defaults: { _controller: AppBundle:University:saveTeacher }
    methods:  [POST]
updateteacher:
    path:     /api/teacher/update
    defaults: { _controller: AppBundle:University:updateTeacher }
    methods:  [POST]

avatar:
    path:     /api/avatar
    defaults: { _controller: AppBundle:University:avatar }
    methods:  [POST]

usergroupops:
    path:     /api/getUserOperations/{tid}
    defaults: { _controller: AppBundle:UserOperations:getUserOperations }
    methods:  [GET]
comment:
    path:     /api/timeline/postComment
    defaults: { _controller: AppBundle:UserOperations:comment }
    methods:  [POST]
like:
    path:     /api/timeline/postLike
    defaults: { _controller: AppBundle:UserOperations:like }
    methods:  [POST]
commentlike:
    path:     /api/timeline/postCommentLike
    defaults: { _controller: AppBundle:UserOperations:commentLike }
    methods:  [POST]
ranking :
    path :     /api/ranking/load
    defaults: { _controller: AppBundle:Ranking:show }
    methods:  [POST]
rankingList :
    path :     /api/ranking/list
    defaults: { _controller: AppBundle:Ranking:rankingList }
    methods:  [POST]